#!/bin/bash

sass -r sass-globbing --update ./src/index.scss:./src/index.css
sass -r sass-globbing --update ./src/components/home/PageHome/PageHome.scss:./src/components/home/PageHome/PageHome.css
sass -r sass-globbing --update ./src/components/footer/TheFooter/TheFooter.scss:./src/components/footer/TheFooter/TheFooter.css
sass -r sass-globbing --update ./src/components/productdetail/DetailsSection/DetailsSection.scss:./src/components/productdetail/DetailsSection/DetailsSection.css
sass -r sass-globbing --update ./src/components/productdetail/AttributeSelect/AttributeSelect.scss:./src/components/productdetail/AttributeSelect/AttributeSelect.css
sass -r sass-globbing --update ./src/components/productdetail/ProductGallery/ProductGallery.scss:./src/components/productdetail/ProductGallery/ProductGallery.css
sass -r sass-globbing --update ./src/components/productdetail/AddToCartForm/AddToCartForm.scss:./src/components/productdetail/AddToCartForm/AddToCartForm.css
sass -r sass-globbing --update ./src/components/productdetail/ProductInfo/ProductInfo.scss:./src/components/productdetail/ProductInfo/ProductInfo.css
sass -r sass-globbing --update ./src/components/productoverview/ProductFilter/Filters/Colors/style.scss:./src/components/productoverview/ProductFilter/Filters/Colors/style.css
sass -r sass-globbing --update ./src/components/productoverview/ProductFilter/ProductFilter.scss:./src/components/productoverview/ProductFilter/ProductFilter.css
sass -r sass-globbing --update ./src/components/productoverview/PageProductOverview/PageProductOverview.scss:./src/components/productoverview/PageProductOverview/PageProductOverview.css
sass -r sass-globbing --update ./src/components/productoverview/ProductQuickView/ProductQuickView.scss:./src/components/productoverview/ProductQuickView/ProductQuickView.css
sass -r sass-globbing --update ./src/components/productoverview/ProductList/ProductList.scss:./src/components/productoverview/ProductList/ProductList.css
sass -r sass-globbing --update ./src/components/productoverview/TopBar/TopBar.scss:./src/components/productoverview/TopBar/TopBar.css
sass -r sass-globbing --update ./src/components/common/Pagination/Pagination.scss:./src/components/common/Pagination/Pagination.css
sass -r sass-globbing --update ./src/components/common/SlideDown/SlideDown.scss:./src/components/common/SlideDown/SlideDown.css
sass -r sass-globbing --update ./src/components/common/HoverDropdown/HoverDropdown.scss:./src/components/common/HoverDropdown/HoverDropdown.css
sass -r sass-globbing --update ./src/components/common/ProductThumbnail/ProductThumbnail.scss:./src/components/common/ProductThumbnail/ProductThumbnail.css
sass -r sass-globbing --update ./src/components/common/Breadcrumb/Breadcrumb.scss:./src/components/common/Breadcrumb/Breadcrumb.css
sass -r sass-globbing --update ./src/components/header/MiniCart/MiniCart.scss:./src/components/header/MiniCart/MiniCart.css
sass -r sass-globbing --update ./src/components/header/TheHeader/TheHeader.scss:./src/components/header/TheHeader/TheHeader.css
sass -r sass-globbing --update ./src/components/header/LoginButton/LoginButton.scss:./src/components/header/LoginButton/LoginButton.css
sass -r sass-globbing --update ./src/assets/scss/_cart.scss:./src/assets/css/_cart.css
sass -r sass-globbing --update ./src/assets/scss/_pop-sidebar.scss:./src/assets/css/_pop-sidebar.css
sass -r sass-globbing --update ./src/assets/scss/_shop-item.scss:./src/assets/css/_shop-item.css
sass -r sass-globbing --update ./src/assets/scss/_my-account-my-orders.scss:./src/assets/css/_my-account-my-orders.css
sass -r sass-globbing --update ./src/assets/scss/_search-not-found.scss:./src/assets/css/_search-not-found.css
sass -r sass-globbing --update ./src/assets/scss/_my-account-returns-exchange.scss:./src/assets/css/_my-account-returns-exchange.css
sass -r sass-globbing --update ./src/assets/scss/_forgot-password.scss:./src/assets/css/_forgot-password.css
sass -r sass-globbing --update ./src/assets/scss/_search-result.scss:./src/assets/css/_search-result.css
sass -r sass-globbing --update ./src/assets/scss/_checkout-shipping.scss:./src/assets/css/_checkout-shipping.css
sass -r sass-globbing --update ./src/assets/scss/_my-account-wishlist.scss:./src/assets/css/_my-account-wishlist.css
sass -r sass-globbing --update ./src/assets/scss/_my-account-personal-details.scss:./src/assets/css/_my-account-personal-details.css
sass -r sass-globbing --update ./src/assets/scss/_product-availability.scss:./src/assets/css/_product-availability.css
sass -r sass-globbing --update ./src/assets/scss/_my-account-my-orders-order.scss:./src/assets/css/_my-account-my-orders-order.css
sass -r sass-globbing --update ./src/assets/scss/_global.scss:./src/assets/css/_global.css
sass -r sass-globbing --update ./src/assets/scss/_checkout-header.scss:./src/assets/css/_checkout-header.css
sass -r sass-globbing --update ./src/assets/scss/_popular-search-phrases.scss:./src/assets/css/_popular-search-phrases.css
sass -r sass-globbing --update ./src/assets/scss/_banners.scss:./src/assets/css/_banners.css
sass -r sass-globbing --update ./src/assets/scss/_error-message.scss:./src/assets/css/_error-message.css
sass -r sass-globbing --update ./src/assets/scss/_checkout-signin.scss:./src/assets/css/_checkout-signin.css
sass -r sass-globbing --update ./src/assets/scss/_pop.scss:./src/assets/css/_pop.css
sass -r sass-globbing --update ./src/assets/scss/_checkout-payment.scss:./src/assets/css/_checkout-payment.css
sass -r sass-globbing --update ./src/assets/scss/_navigation.scss:./src/assets/css/_navigation.css
sass -r sass-globbing --update ./src/assets/scss/_signup-box.scss:./src/assets/css/_signup-box.css
sass -r sass-globbing --update ./src/assets/scss/_general.scss:./src/assets/css/_general.css
sass -r sass-globbing --update ./src/assets/scss/_checkout-confirmation.scss:./src/assets/css/_checkout-confirmation.css
sass -r sass-globbing --update ./src/assets/scss/_my-account-login.scss:./src/assets/css/_my-account-login.css
sass -r sass-globbing --update ./src/assets/scss/common.scss:./src/assets/css/common.css
sass -r sass-globbing --update ./src/assets/scss/_icon-font.scss:./src/assets/css/_icon-font.css
sass -r sass-globbing --update ./src/assets/scss/main.scss:./src/assets/css/main.css
sass -r sass-globbing --update ./src/assets/scss/_my-account-address-book.scss:./src/assets/css/_my-account-address-book.css
sass -r sass-globbing --update ./src/assets/scss/_jqzoom.scss:./src/assets/css/_jqzoom.css
sass -r sass-globbing --update ./src/assets/scss/_pagination.scss:./src/assets/css/_pagination.css
sass -r sass-globbing --update ./src/assets/scss/_my-account-returns-exchange-order.scss:./src/assets/css/_my-account-returns-exchange-order.css
sass -r sass-globbing --update ./src/assets/scss/_size-guide.scss:./src/assets/css/_size-guide.css
sass -r sass-globbing --update ./src/assets/scss/_wishlist.scss:./src/assets/css/_wishlist.css
sass -r sass-globbing --update ./src/assets/scss/_add-to-wishlist-btn.scss:./src/assets/css/_add-to-wishlist-btn.css
sass -r sass-globbing --update ./src/assets/scss/_mixins.scss:./src/assets/css/_mixins.css
sass -r sass-globbing --update ./src/assets/scss/_contact-form.scss:./src/assets/css/_contact-form.css
sass -r sass-globbing --update ./src/assets/scss/_faq.scss:./src/assets/css/_faq.css
sass -r sass-globbing --update ./src/assets/scss/_footer.scss:./src/assets/css/_footer.css
sass -r sass-globbing --update ./src/assets/scss/_quickview.scss:./src/assets/css/_quickview.css
sass -r sass-globbing --update ./src/assets/scss/_mix-match.scss:./src/assets/css/_mix-match.css
sass -r sass-globbing --update ./src/assets/scss/_checkout-thankyou.scss:./src/assets/css/_checkout-thankyou.css
sass -r sass-globbing --update ./src/assets/scss/_login-box.scss:./src/assets/css/_login-box.css
sass -r sass-globbing --update ./src/assets/scss/_pdp.scss:./src/assets/css/_pdp.css
sass -r sass-globbing --update ./src/assets/scss/_my-account-payment-details.scss:./src/assets/css/_my-account-payment-details.css
sass -r sass-globbing --update ./src/assets/scss/_custom-language.scss:./src/assets/css/_custom-language.css
sass -r sass-globbing --update ./src/assets/scss/_store-finder.scss:./src/assets/css/_store-finder.css
sass -r sass-globbing --update ./src/assets/scss/_mix-match-product.scss:./src/assets/css/_mix-match-product.css
sass -r sass-globbing --update ./src/assets/scss/_home.scss:./src/assets/css/_home.css
sass -r sass-globbing --update ./src/assets/scss/_imprint.scss:./src/assets/css/_imprint.css
sass -r sass-globbing --update ./src/assets/scss/_store-location.scss:./src/assets/css/_store-location.css
sass -r sass-globbing --update ./src/assets/scss/_input-fields.scss:./src/assets/css/_input-fields.css
sass -r sass-globbing --update ./src/assets/scss/_megamenu.scss:./src/assets/css/_megamenu.css
